### ISSUE TITLE
BIOG MAIN

### ISSUE THREAD

**Issue by hanfengsunshine** [MrQianJinSi/poetry_analyzer#4]
![ddpck95a4 f1a c6 z2w](https://cloud.githubusercontent.com/assets/14012055/25807569/e48ff6d4-3439-11e7-906c-444808e54bd7.png)
![image](https://cloud.githubusercontent.com/assets/14012055/25807592/f9716a38-3439-11e7-86e0-483dc4788010.png)

 小白拜读您的code, 但是折腾了一下跑通，想问为什么没有BIOG MAIN 呢？ 
 可以留个联系方式？麻烦您了！

**Comment by MrQianjinsi** [comment]
你好
不用python，直接用数据库软件能看到BIOG_MAIN中的数据吗？
如果能看到的话，请再确认一下数据库和程序的相对路径关系。

2017-05-08 22:03 GMT+08:00 hanfengsunshine <notifications@github.com>:
