### ISSUE TITLE
用 Wikidata 分析关联和自动推理

### ISSUE THREAD

**Issue by erickguan** [MrQianJinSi/poetry_analyzer#5]
你好，前进四先生。最近在做知识图谱的研究，然后突然想到了你的文章。我正好想到一个主意，如果根据 CBDB 的数据和全唐诗，可以用什么样的模型去自动推理有趣的规则。
我先试着把 CBDB 的人名数据导入进 wikidata，大概做了 90 万次编辑，然而还有更多关联数据需要导入。这就是我这周做的事。不过有了这想法，就让我先在这里抛砖引玉了。

**Comment by MrQianjinsi** [comment]
这个想法很有趣哦。CBDB是一个大而全的数据库，如果能全部图谱化，应当可以做出一些很好玩的查询，比如出生在天宝年间的诗人有哪些？有哪些诗人经历了安史之乱？哪些诗人做过部级以上干部？
我建议还是先根据自己需要的查询，来设计图谱数据库，这样更有的放矢一些。先从一些小的查询开始，慢慢增加功能。

在 2017年12月16日 上午12:33，Erick Guan <notifications@github.com>写道：

**Comment by erickguan** [comment]
> 我建议还是先根据自己需要的查询，来设计图谱数据库，这样更有的放矢一些。先从一些小的查询开始，慢慢增加功能。

对，是这个道理。不过这个数据库存储倒是不难，麻烦一些的部分大概是导入数据。我自己导入数据（大概有 90 万次编辑）这件事我也和 CBDB 的人说过了一下。我知道的最简单的应用其实是 https://tools.wmflabs.org/reasonator/?q=Q7071。根据链接自动生成摘要和时间线。

> 这个想法很有趣哦。CBDB是一个大而全的数据库，如果能全部图谱化，应当可以做出一些很好玩的查询，比如出生在天宝年间的诗人有哪些？有哪些诗人经历了安史之乱？哪些诗人做过部级以上干部？

这个想法很棒啊！SPARQL 确实很容易把这些索引出来。经历过安史之乱的诗人： http://tinyurl.com/y7elhfaj

**Comment by zhanpx** [comment]
你好，我已收到你的邮件，我会及时处理^_^
